# Ансамбли моделей машинного обучения. Часть 2.

In [2]:
import pandas as pd

### 1. Выберите набор данных (датасет) для решения задачи классификации или регресии.

Используем данные из Healthy Diet & Calorie Intake: Nutrition & Health https://www.kaggle.com/datasets/aliyasaly1231/healthy-diet-and-calorie-intake

In [3]:
data = pd.read_csv('healthy_diet_calorie_intake.csv', sep=",")

In [4]:
# размер набора данных
data.shape

(6000, 15)

In [5]:
# типы колонок
data.dtypes

Person_ID                        str
Age                            int64
Gender                           str
Height_cm                    float64
Weight_kg                    float64
BMI                          float64
Activity_Level                   str
Daily_Calorie_Requirement      int64
Daily_Calorie_Consumed         int64
Protein_Intake_g             float64
Carbohydrate_Intake_g        float64
Fat_Intake_g                 float64
Water_Intake_Liters          float64
Diet_Type                        str
Health_Status                    str
dtype: object

### 2. В случае необходимости проведите удаление или заполнение пропусков и кодирование категориальных признаков.

In [6]:
data.isnull().sum()

Person_ID                    0
Age                          0
Gender                       0
Height_cm                    0
Weight_kg                    0
BMI                          0
Activity_Level               0
Daily_Calorie_Requirement    0
Daily_Calorie_Consumed       0
Protein_Intake_g             0
Carbohydrate_Intake_g        0
Fat_Intake_g                 0
Water_Intake_Liters          0
Diet_Type                    0
Health_Status                0
dtype: int64

In [7]:
data.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,P0001,50,Male,176.4,74.8,24.0,Very Active,2852,2625,183.0,16.9,202.8,3.3,Keto,Healthy
1,P0002,18,Female,167.6,75.5,26.9,Sedentary,1904,2044,90.1,306.5,50.8,1.9,Vegan,Overweight
2,P0003,68,Female,161.9,87.2,33.3,Lightly Active,2009,2540,222.7,281.3,58.2,2.4,High Protein,Obese
3,P0004,22,Female,169.3,66.9,23.3,Moderately Active,2318,2096,69.5,299.8,68.7,2.9,Balanced,Healthy
4,P0005,30,Male,179.1,75.3,23.5,Sedentary,2144,1937,32.9,285.6,73.7,2.2,Balanced,Healthy

Я выбрал регрессию по weight_kg но у нас есть категориальные признаки, закодирую их с LabelEncoding

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data = data.drop('Person_ID', axis=1)

data['Gender'] = le.fit_transform(data['Gender'])
data['Activity_Level'] = le.fit_transform(data['Activity_Level'])
data['Diet_Type'] = le.fit_transform(data['Diet_Type'])
data['Health_Status'] = le.fit_transform(data['Health_Status'])

In [9]:
data.head()

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,50,1,176.4,74.8,24.0,4,2852,2625,183.0,16.9,202.8,3.3,2,0
1,18,0,167.6,75.5,26.9,3,1904,2044,90.1,306.5,50.8,1.9,4,2
2,68,0,161.9,87.2,33.3,1,2009,2540,222.7,281.3,58.2,2.4,1,1
3,22,0,169.3,66.9,23.3,2,2318,2096,69.5,299.8,68.7,2.9,0,0
4,30,1,179.1,75.3,23.5,3,2144,1937,32.9,285.6,73.7,2.2,0,0

### 3. С использованием метода train_test_split разделите выборку на обучающую и тестовую.

In [10]:
X = data.drop('Weight_kg', axis=1)
y = data['Weight_kg']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.4,
    random_state=42
)

print("Размер обучающей выборки:", X_train.shape)
print("Размер тестовой выборки:", X_test.shape)
print("Размер y_train:", y_train.shape)
print("Размер y_test:", y_test.shape)

Размер обучающей выборки: (3600, 13)
Размер тестовой выборки: (2400, 13)
Размер y_train: (3600,)
Размер y_test: (2400,)

### 4. Обучите следующие ансамблевые модели

#### Одну из моделей группы стекинга.

Стекинг (Stacking) — ансамблевый метод машинного обучения, в котором используется несколько моделей первого уровня и отдельная модель второго уровня (мета-ученик). Модели первого уровня обучаются независимо друг от друга и формируют прогнозы. Полученные прогнозы используются как входные признаки для модели второго уровня, которая строит окончательное предсказание. В данной работе в качестве моделей первого уровня использовались линейная регрессия, дерево решений и случайный лес, а в качестве мета-ученика — линейная регрессия. Такой подход позволяет объединить преимущества различных алгоритмов и повысить качество прогнозирования.

In [11]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [12]:
#создание стекинга
base_models = [
    ('lr', LinearRegression()),
    ('tree', DecisionTreeRegressor(random_state=42)),
    ('rf', RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ))
]

stacking = StackingRegressor(
    estimators=base_models,
    final_estimator=LinearRegression()
)

#обучение
stacking.fit(X_train, y_train)

StackingRegressor(estimators=[('lr', LinearRegression()),
                              ('tree', DecisionTreeRegressor(random_state=42)),
                              ('rf', RandomForestRegressor(random_state=42))],
                  final_estimator=LinearRegression())

In [13]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

y_pred_stack = stacking.predict(X_test)

print("Stacking Regressor")
print("MAE =", mean_absolute_error(y_test, y_pred_stack))
print("MSE =", mean_squared_error(y_test, y_pred_stack))
print("R² =", r2_score(y_test, y_pred_stack))

Stacking Regressor
MAE = 0.4204761403161985
MSE = 0.4628842030883345
R² = 0.9969663337507328

Качество отдельных моделей

In [14]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=42
    )
}

for name, model in models.items():
    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    print(name)
    print("R² =", r2_score(y_test, pred))
    print()

Linear Regression
R² = 0.9917098224318054

Decision Tree
R² = 0.988430598682623

Random Forest
R² = 0.9954427055375525

#### Модель многослойного персептрона

Многослойный персептрон (Multi-Layer Perceptron, MLP) представляет собой искусственную нейронную сеть прямого распространения сигнала. Сеть состоит из входного слоя, одного или нескольких скрытых слоев и выходного слоя. Каждый нейрон скрытого слоя выполняет взвешенное суммирование входных сигналов и применяет функцию активации.

Обучение сети осуществляется методом обратного распространения ошибки (Backpropagation), при котором веса нейронов корректируются для минимизации функции потерь.

В задаче регрессии используется класс MLPRegressor, который прогнозирует непрерывные значения. Для повышения эффективности обучения входные признаки предварительно масштабируются с помощью стандартизации (StandardScaler), поскольку многослойный персептрон чувствителен к масштабу данных.

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
from sklearn.neural_network import MLPRegressor

mlp = MLPRegressor(
    hidden_layer_sizes=(100, 50),  # два скрытых слоя
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

mlp.fit(X_train_scaled, y_train)

MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)

In [18]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

y_pred = mlp.predict(X_test_scaled)

print("MLP Regressor")
print("MAE =", mean_absolute_error(y_test, y_pred))
print("MSE =", mean_squared_error(y_test, y_pred))
print("R² =", r2_score(y_test, y_pred))

MLP Regressor
MAE = 0.2712133984881581
MSE = 0.14118349307828357
R² = 0.9990747068164184

#### (дополнительно) двумя методами на выбор из семейства МГУА

gmdh не работает на новом питоне

In [39]:
from gmdh import Combi, Mia
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

ModuleNotFoundError: No module named 'gmdh'

In [ ]:
combi = Combi()

combi.fit(X_train, y_train)

y_pred_combi = combi.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_combi)
mse = mean_squared_error(y_test, y_pred_combi)
r2 = r2_score(y_test, y_pred_combi)

print("COMBI")
print("MAE =", mae)
print("MSE =", mse)
print("R2 =", r2)

In [30]:
mia = Mia()

mia.fit(X_train, y_train)

y_pred_mia = mia.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_mia)
mse = mean_squared_error(y_test, y_pred_mia)
r2 = r2_score(y_test, y_pred_mia)

print("MIA")
print("MAE =", mae)
print("MSE =", mse)
print("R2 =", r2)

NameError: name 'Mia' is not defined

### 5. Оцените качество моделей с помощью одной из подходящих для задачи метрик. Сравните качество полученных моделей.

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

results = []

for name, model in models.items():
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append([name, mae, mse, r2])

import pandas as pd

df_results = pd.DataFrame(results, columns=["Model", "MAE", "MSE", "R2"])
df_results = df_results.sort_values(by="MAE")

df_results

               Model       MAE       MSE        R2
2      Random Forest  0.408259  0.695363  0.995443
0  Linear Regression  0.782914  1.264936  0.991710
1      Decision Tree  0.880292  1.765287  0.988431

В ходе эксперимента были обучены три регрессионные модели:
линейная регрессия, дерево решений и случайный лес. Для оценки качества использовались метрики MAE, MSE и R².

Наилучшие результаты показала модель Random Forest, которая имеет:

- минимальную ошибку MAE = 0.408
- минимальную ошибку MSE = 0.695
- максимальное значение коэффициента детерминации R² = 0.995

Это означает, что модель объясняет около 99.5% вариации целевой переменной, что свидетельствует о очень высокой точности предсказаний.


Можно сделать вывод, что:

- ансамблевые методы (особенно Random Forest) обеспечивают наилучшую точность;
- линейные модели дают стабильный, но менее точный результат;
- одиночное дерево решений уступает более сложным моделям.